package Locators;

public class Objectlocators {
	public static final String logo="//*[@id='hirepro'] | //*[@src='assets/img/Hireprous.png']";
	public static final String UserName="email";
	public static final String Password="password";
	public static final String loginBtn= "//*[@class='btn btn-primary form-control']";
	public static final String Servicetab= "//*[@id='services'] | //*[@routerlink='/hirepros/services-menu']";
	public static final String Resourcemanag= "(//*[@class='read-more'])[1] | (//*[@title='More Details'])[1]";
	public static final String Newresource= "//*[@class='dropdown-toggle btn btn-primary btn-sm']";
	public static final String empid= "//*[@name='employeeIdByHR']";
	public static final String workno= "//*[@name='workOrderNumber'] | (//*[@class='form-control ng-untouched ng-pristine ng-invalid'])[2]";
	public static final String emptype= "//*[@name='employmentType'] | (//*[@class='form-select ng-untouched ng-pristine ng-invalid'])[1]";
	public static final String empfname= "//*[@name='firstName'] | //*[@class='form-control ng-untouched ng-pristine ng-invalid'][4]";
	public static final String emplanme= "//*[@name='lastName'] | //*[@class='form-control ng-untouched ng-pristine ng-invalid'][5]";
	public static final String empcontact= "//*[@name='contactNumber'] | //*[@class='form-control ng-untouched ng-pristine ng-invalid'][6]";
	public static final String empemail= "//*[@name='email'] | //*[@class='form-control ng-untouched ng-pristine ng-invalid'][7]";
	public static final String rgender="//*[@id='inlineRadio1'] | (//*[@class='form-check-input ng-untouched ng-pristine ng-invalid'])[1]";
	public static final String projectallocatione= "//*[@name='projectAllocation'] | (//*[@class='form-select ng-untouched ng-pristine ng-invalid'])[2]";
	public static final String customername= "//*[@class='form-select ng-untouched ng-pristine ng-valid']";
	public static final String projectname= "//*[@name='projectId']";
	public static final String BU= "//*[@name='buId']";
	public static final String designation="//*[@name='designation']";
	public static final String yearofexp= "//*[@name='experience']";
	public static final String skillset= "//*[@name='skillSet']";
	public static final String savebtn= " //*[@class='form-control btn btn-primary']";
	public static final String Name= "(//*[@name='fullName'])[1]";
	public static final String searchbtn= "(//*[@class='btn btn-primary'])[2]";
	public static final String vendormenu= "(//*[@class='read-more'])[2]";
	//////////////////////////vendor/////////////////////////////////////////////////////////////////
	public static final String vendorlist="//*[@id=\"tab2\"]/div/div/div/div/div[1]/div[1]";
	public static final String vendorsearch= "//*[@class='form-control ng-pristine ng-invalid ng-touched']";
	public static final String Newvendorbtn="//*[@class='dropdown-toggle btn btn-primary btn-sm']";
	public static final String Editvendorbtn="(//*[@class='dropdown-toggle btn btn-tbl-edit btn-xs'])[1]";
	public static final String Deletevendorbtn="(//*[@class='dropdown-toggle btn btn-tbl-delete btn-xs'])[1]";
	public static final String vendorName="//*[@name='vendorName']";
	public static final String vendorEmail="//*[@name='email']";
	public static final String vendorContactNo="//*[@name='contactNumber']";
	public static final String vendorLocation="//*[@name='location']";
	public static final String vendorpriority= "//*[@class='form-select ng-untouched ng-pristine ng-valid']";
	public static final String vendorAddress="//*[@name='address']";
	public static final String vendorCCEmail="//*[@name='ccEmailIds']";
	public static final String vendorSave="//*[@value='Save']";
	//////////////////////////////////////////////job request////////////////////////////////////
	public static final String dashboard="//*[@id='dashboard'] | //*[@class='nav-link active']";
	public static final String Recbtn="//*[@id='recruitment']"; 
	public static final String recprocess="//*[@id='what-we-do']/div/div/h2 | //*[@class='section-title']";
	public static final String jobrequest="(//*[@class='read-more'])[1] | (//*[@title='More Details'])[1]";
	public static final String jobrequeslist="//*[@id='tab1']/div/div/div/div/div/div[1]/div[1] | //*[@class='col-md-2 col-md-2 text-muted']";
	public static final String jobrequessearch="//*[@placeholder='Search for Job Request'] | (//*[@name='jrNumber'])[1]";
	public static final String newjobrequest="//*[@class='dropdown-toggle btn btn-primary btn-sm'] | //*[@style='font-size: 12px;']";
	public static final String addjobrequest="/html/body/app-root/app-home/app-add-job-request/div/div[2]/div[1]/div/div[1]/header";
	public static final String customerfield="//*[@id='bar-parent10']/form/div[1]/div[1]/div/select | //*[@name='customerId']";
	public static final String rrole="//*[@id='bar-parent10']/form/div[1]/div[2]/div/select | //*[@name='roleId']";
	public static final String bunit="//*[@id='bar-parent10']/form/div[1]/div[3]/div/select | //*[@name='buId']";
	public static final String currencytype="//*[@id='bar-parent10']/form/div[2]/div[2]/div/select | //*[@name='currency']";
	public static final String payfreq="//*[@id='bar-parent10']/form/div[2]/div[4]/div/select | //*[@name='payFrequency']";
	public static final String employeetype="//*[@id='bar-parent10']/form/div[3]/div[1]/div/select | //*[@name='employmentType']";
	public static final String projectstartdate="//*[@name='projectStartDate'] | //*[@name='projectStartDate']";
	public static final String placementfor="//*[@id='bar-parent10']/form/div[4]/div[1]/div/select | //*[@name='placementFor']";
	public static final String remoteworking="//*[@id='bar-parent10']/form/div[4]/div[2]/div/select | //*[@name='remoteOption']";
	public static final String recruiter="//*[@id='bar-parent10']/form/div[4]/div[3]/div/select | //*[@name='recruiterId']";
	public static final String nop="(//*[@class='form-control ng-untouched ng-pristine ng-invalid'])[1] | (//*[@name='noOfOpenings'])";
	public static final String location1="(//*[@class='form-control ng-untouched ng-pristine ng-valid'])[1] | (//*[@name='location'])";
	public static final String payrange="//*[@name='payRange'] | (//*[@class='form-control ng-untouched ng-pristine ng-invalid'])[2]";
	public static final String contractduration="//*[@name='contractDuration'] | //*[@class='form-control ng-untouched ng-pristine']";
	public static final String jobdescription="//*[@id='bar-parent10']/form/div[5]/div/div/textarea | //*[@name='jobDescription']";
	public static final String mandatoryskills= "//*[@id='bar-parent10']/form/div[6]/div[1]/div/textarea | //*[@name='mandatorySkills']";
	public static final String optionalskills="//*[@id='bar-parent10']/form/div[6]/div[2]/div/textarea | //*[@name='optionalSkills']";
	public static final String Savejobrequest="//*[@value='Save'] | (//*[@class='form-control btn btn-primary'])[1]";
	public static final String jobsearch="(//*[@name='jrNumber'])[1] | //*[@placeholder='Search for Job Request']";
}
